# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from config_routing.grpc import initiatelink_pb2 as config__routing_dot_grpc_dot_initiatelink__pb2


class InitiateLinkControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchMerchantData = channel.unary_unary(
                '/config_routing.InitiateLinkController/FetchMerchantData',
                request_serializer=config__routing_dot_grpc_dot_initiatelink__pb2.ListRequest.SerializeToString,
                response_deserializer=config__routing_dot_grpc_dot_initiatelink__pb2.ListResponseMerchantData.FromString,
                )
        self.FetchSubMerchantData = channel.unary_unary(
                '/config_routing.InitiateLinkController/FetchSubMerchantData',
                request_serializer=config__routing_dot_grpc_dot_initiatelink__pb2.ListRequest.SerializeToString,
                response_deserializer=config__routing_dot_grpc_dot_initiatelink__pb2.ListResponseSubMerchantData.FromString,
                )


class InitiateLinkControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchMerchantData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchSubMerchantData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InitiateLinkControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchMerchantData': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchMerchantData,
                    request_deserializer=config__routing_dot_grpc_dot_initiatelink__pb2.ListRequest.FromString,
                    response_serializer=config__routing_dot_grpc_dot_initiatelink__pb2.ListResponseMerchantData.SerializeToString,
            ),
            'FetchSubMerchantData': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchSubMerchantData,
                    request_deserializer=config__routing_dot_grpc_dot_initiatelink__pb2.ListRequest.FromString,
                    response_serializer=config__routing_dot_grpc_dot_initiatelink__pb2.ListResponseSubMerchantData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config_routing.InitiateLinkController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InitiateLinkController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchMerchantData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/config_routing.InitiateLinkController/FetchMerchantData',
            config__routing_dot_grpc_dot_initiatelink__pb2.ListRequest.SerializeToString,
            config__routing_dot_grpc_dot_initiatelink__pb2.ListResponseMerchantData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchSubMerchantData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/config_routing.InitiateLinkController/FetchSubMerchantData',
            config__routing_dot_grpc_dot_initiatelink__pb2.ListRequest.SerializeToString,
            config__routing_dot_grpc_dot_initiatelink__pb2.ListResponseSubMerchantData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
